# Site settings
title: GeoWatch
email:
description:
baseurl: "/geowatch"
url: "http://yourdomain.com" # the base hostname & protocol for your site
twitter_username:
github_username:

# Build settings
markdown: kramdown

# Prose.io Config
prose:
  rooturl: ''
  siteurl: 'http://jakoblo.github.io/geowatch/'
  relativeLinks: 'http://jakoblo.github.io/geowatch/links.jsonp'
  # 	media: 'media'
  ignore:
    - index.md
    - .gitignore
    - links.jsonp
    - _config.yml
    - /_layouts
    - /_includes
    - /_layouts
    - /_sass
    - /css
  metadata:
    _posts:
      - name: "layout"
        field:
          element: "hidden"
          value: "post"
      - name: "title"
        field:
          element: "text"
          label: "Title"
          value: "title"
      - name: "description"
        field:
          element: "text"
          label: "Description"
          value: ""
      - name: "categories"
        field:
          element: "text"
          label: "Categories"
          value: "blog"
      - name: "thumbnail"
        field:
          element: "text"
          label: "Thumbnail Path"
          value: "/img/thumb.png"
      - name: "site-url"
        field:
          element: "text"
          label: "Site URL"
          value: ""
      - name: "published"
        field:
         element: "button"
         label: "instant publish?"
         on: "YES"
         off: "NO"
