# Site settings
title: GeoWatch
email:
description:
baseurl: "/geowatch"
url: "http://yourdomain.com" # the base hostname & protocol for your site
twitter_username:
github_username:

# Build settings
markdown: kramdown
